spring:
  profiles:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        auto-ddl:
        dialect: org.hibernate.dialect.MariaDBDialect
#  h2:
#    console:
#     enabled: false

spring.profiles.include: real-db
